name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  check_test_file:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if test script exists
        run: |
          if [ ! -f "test.cpp" ]; then
            echo "Test file not found" > napaka.txt
          fi

  build_and_test:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [macos-latest] 
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake
        run: |
          case "${{ matrix.os }}" in
           "macos-latest") 
             brew install cmake
             ;;
          esac

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

      - name: Build
        run: |
          echo "Current working directory: $(pwd)"
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

      - name: Compile Main
        run: g++ main.cpp test.cpp -o build/main

      - name: Run first test
        run: |
            ${{github.workspace}}/build/main test_kmp "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
            if [[ $? -ne 0 ]]; then
              echo "Napaka pri izvajanju programa"
            fi

      - name: Run second test
        run: |
            ${{github.workspace}}/build/main test_sunday "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
            if [[ $? -ne 0 ]]; then
              echo "Napaka pri izvajanju programa"
            fi
