name: Docker and Deploy

on:
  workflow_run:
    workflows: ["CMake"]
    types:
      - completed
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          
      - name: Build Docker image
        run: docker build -t kmp_sunday .
 
      - name: Push Docker image to DockerHub
        run: docker push kmp_sunday