name: Docker and Deploy

on:
  workflow_run:
    workflows: ["CMake"]
    types:
      - completed #skripta se pricne ko se Cmake torej prejsna skripta zakljuci
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPONAME: ${{ secrets.REPO_NAME }}
  #definiramo spremenljivke za docker ime,geslo in ime repozitorija
jobs:
  deploy:
    runs-on: self-hosted #izvajamo na lastnem action runnerju
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to DockerHub 
        uses: docker/login-action@v1 # Uporabi akcijo za prijavo v DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #z imenom ki je zapisan v github secrets 
          password: ${{ secrets.DOCKER_PASSWORD }} #z geslom ki je zapisan v github secrets 

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest .  # Ustvarimo sliko Docker z imenom dockerhuba in imenom repozitorija kot del imena slike

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest # potisnemo sliko na repozitorij in kot razlicico podamo "latest"