name: CMake

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  check_test_file:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if test script exists
      shell: bash
      run: |
        if [ ! -f "test.cpp" ]; then
          echo "Test file not found" > napaka.txt
        fi

  build_and_test:
    needs: check_test_file  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Check for errors
      shell: bash
      run: |
        if [ -f "napaka.txt" ]; then
          if [ "$(cat napaka.txt)" = "Test file not found" ]; then
            echo "Napaka: Test file not found"
            exit 1
          fi
        fi

    - name: Install CMake
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          choco install cmake
        elif [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y cmake g++
        else
          brew install cmake
        fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Compile Main
      run: g++ main.cpp test.cpp -o build/main

    - name: Run first test
      shell: bash
      run: |
          if [ "${RUNNER_OS}" == "Windows" ]; then
            ${{github.workspace}}/build/main test_kmp "znanstveniki" ${{GITHUB_WORKSPACE}}\cmake-build-debug\test-besedilo.txt
          else 
           ${{github.workspace}}/build/main test_kmp "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
          fi

    - name: Run second test
      shell: bash
      run: |
          if [ "${RUNNER_OS}" == "Windows" ]; then
            ${{github.workspace}}/build/main test_kmp "znanstveniki" ${{GITHUB_WORKSPACE}}\cmake-build-debug\test-besedilo.txt
          else 
            ${{github.workspace}}/build/main test_sunday "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
          fi