name: CMake on a single platform

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

  workflow_dispatch:

env:

  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

  BUILD_TYPE: Release

jobs:

  build:

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.

    # You can convert this to a matrix build if you need cross-platform coverage.

    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/vaja2_algoritmi/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/vaja2_algoritmi

    - name: Build
      run: cmake --build ${{github.workspace}}/vaja2_algoritmi/build --config ${{env.BUILD_TYPE}}

    - name: Compile Main
      run: g++ /home/vboxuser/Desktop/actions-runner/_work/vaja2_algoritmi/vaja2_algoritmi/vaja2_algoritmi/main.cpp /home/vboxuser/Desktop/actions-runner/_work/vaja2_algoritmi/vaja2_algoritmi/vaja2_algoritmi/test.cpp -o /home/vboxuser/Desktop/actions-runner/_work/vaja2_algoritmi/vaja2_algoritmi/vaja2_algoritmi/build/main

    - name: Run Found Executable
      run: ${{github.workspace}}/vaja2_algoritmi/build/main 1 "znanstveniki" /home/runner/work/vaja2_algoritmi/vaja2_algoritmi/vaja2_algoritmi/cmake-build-debug/test-besedilo.txt

    - name: Show output.txt content
      run: cat out.txt