name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build_and_test:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [windows-latest] 
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake
        run: choco install cmake

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

      - name: Build
        run: |
          echo "Current working directory: $(pwd)"
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

      - name: Compile Main
        run: g++ main.cpp test.cpp -o build/main

      - name: Run first test
        run: |
            ${{github.workspace}}/build/main test_kmp "znanstveniki" ${GITHUB_WORKSPACE}/cmake-build-debug/test-besedilo.txt
      
      - name: Print current directory path and list directories
        shell: bash
        run: |
            echo "Trenutna pot: $(pwd)"
            echo "Mape v trenutni poti:"
            ls -d */

            


            
