name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build ./ --config ${{env.BUILD_TYPE}}

    - name: Compile Main
      run: g++ main.cpp test.cpp -o main

    - name: Run Found Executable
      run: |
          ./main test_kmp "znanstveniki" cmake-build-debug/test-besedilo.txt
          if [[ $? -ne 0 ]]; then
            echo "Napaka pri izvajanju programa" > napaka.txt
          fi

    - name: Show error output
      run: cat napaka.txt

    - name: Show output.txt content
      run: cat out.txt
