name: Docker and Deploy

on:
  workflow_run:
    workflows: ["CMake"]
    types:
      - completed
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPONAME: ${{ secrets.REPO_NAME }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Current time
        id: datum
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date

      - name: Push Docker image to DockerHub
        run: docker push $DOCKER_USERNAME/$REPONAME:$date
