name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build_and_test:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [windows-latest] 
    steps:
      - uses: actions/checkout@v3

      - name: Install CMake
        run: choco install cmake

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

      - name: Build
        run: |
          echo "Current working directory: $(pwd)"
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

      - name: Compile Main
        run: g++ main.cpp test.cpp -o build/main

      - name: Check if out.txt exists
        shell: bash
        run: |
            if [ -f "out.txt" ]; then
              echo "File out.txt exists"
            else
              echo "File out.txt does not exist"
            fi
      - name: Find test-besedilo.txt
        shell: pwsh
        run: |
            $filePath = Get-ChildItem -Path "C:\" -Recurse -Filter "test-besedilo.txt" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
              if ($filePath) {
                Write-Output "Path to test-besedilo.txt: $filePath"
                Write-Output "##[set-output name=file_path]$filePath"
            } else {
                Write-Output "File test-besedilo.txt not found."
              }


            
